variable "v_mi_deregistration_global_tags" {}
variable "v_mi_deregistration_poos_tags" {}
variable "v_mi_deregistration_account_id" {}
variable "v_mi_deregistration_region" {}
variable "v_mi_deregistration_function_name" {}
variable "v_mi_deregistration_s3_bucket" {}
variable "v_mi_deregistration_kms_key_arn" {}
variable "v_mi_deregistration_s3_bucket_athena_query_result" {}
variable "v_mi_deregistration_global_resource_sync_database" {}
variable "v_mi_deregistration_iam_role_automation_execution" {}
variable "v_mi_deregistration_ssm_sns_arn" {}
variable "v_mi_deregistration_tag_handler_ecs_lambda" {}
